create table DM.DM_F101_ROUND_F
(
FROM_DATE DATE,
TO_DATE DATE,
CHAPTER VARCHAR(1),
LEDGER_ACCOUNT VARCHAR(5),
CHARACTERISTIC VARCHAR(1),
BALANCE_IN_RUB NUMERIC(23,8),
BALANCE_IN_VAL NUMERIC(23,8),
BALANCE_IN_TOTAL NUMERIC(23,8),
TURN_DEB_RUB NUMERIC(23,8),
TURN_DEB_VAL NUMERIC(23,8),
TURN_DEB_TOTAL NUMERIC(23,8),
TURN_CRE_RUB NUMERIC(23,8),
TURN_CRE_VAL NUMERIC(23,8),
TURN_CRE_TOTAL NUMERIC(23,8),
BALANCE_OUT_RUB NUMERIC(23,8),
BALANCE_OUT_VAL NUMERIC(23,8),
BALANCE_OUT_TOTAL NUMERIC(23,8)
)